### ISSUE TITLE
Highlighting is applied by default not only when outputclass is set

### ISSUE THREAD

**Issue by logronio** [jason-fox/fox.jason.prismjs#10]
A content with &lt;codeph&gt; without an outputclass is highlighted by default. Is it the normal behavior? Is it possible to highlight only when the outputclass="language-xxxx" is present in element or ancestor element (like body)?

sample codeph:
`<codeph>&lt;amount&gt;</codeph>`

sample output:
![image](https://user-images.githubusercontent.com/61045086/151137477-e36636b8-1235-4cf0-ac10-6d77b62445d8.png)

**Comment by jason-fox** [comment]
It currently highlights every `<codeblock>` and `<codeph>` - use `<codeblock outputclass="language-none">`  to avoid highlighting.

[This](https://github.com/jason-fox/fox.jason.prismjs/blob/master/xsl/add-code-id.xsl#L26) is the line that is checking for every `<codeblock>` and `<codeph>`

If you need to, you could modify 

```xml
<xsl:template match="codeph|codeblock">
```

to

```xml
<xsl:template match="codeph[contains(@outputclass,' language-') |codeblock[contains(@outputclass,' language- ') ">
```

It won't work for ancestors, but that would just need another clause.

**Comment by logronio** [comment]
Thanks. I'll try your suggestion on template.

I tried your suggestion to avoid highlighting. It is producing an error.
Sample codeph:
`<codeph outputclass="language-none">&lt;amount&gt;</codeph>`

**Comment by jason-fox** [comment]
It's working for me - can you supply your error log?

**Comment by logronio** [comment]
The error is kinda weird cause its happening in the other dita ot process not in the prismjs part. If I remove, the outputclass="language-none", it builds perfectly fine.

Anyways, I modify the template into
`<xsl:template match="codeph[contains(@outputclass,'language-') or ancestor::body[contains(@outputclass,'language-')]] | codeblock[contains(@outputclass,'language-') or ancestor::body[contains(@outputclass,'language-')]] ">`

It works perfectly fine. 
Thanks.
