### ISSUE TITLE
Customize font size in PDF output

### ISSUE THREAD

**Issue by hcw70** [jason-fox/fox.jason.prismjs#12]
I have trouble customizing the font size in highlighted codeblocks using this plugin.

Default size seems to be too small,

compared to the other font we use,
so i tried to increase the "font-size" in style.css to 2em, but did not see any difference in PDF output.

CSS sounds also only affecting HTML output to me. 
Our non-highlighted codeblocks can be customized via   

`<xsl:attribute-set name="codeblock"/>
`
in pr-domain-attr.xsl successfully however.

Any hint would be appreciated.

See screenshot:
*******************************
![Screenshot_20220622_151625](https://user-images.githubusercontent.com/1888459/175258979-9ad4f95f-e298-4241-89d1-890c6e65c10d.png)
******************************

**Comment by jason-fox** [comment]
Altering the CSS will only change the HTML outputs. The PDF highlighting [inherits](https://github.com/jason-fox/fox.jason.prismjs/blob/master/cfg/fo/attrs/prismjs-attr.xsl#L15-L24 ) values from an `attribute-set` called `codeblock`, which in turn inherits from `pre`and `base-font` which include the printable font sizing from the standard PDF plugin. 

```xsl
<xsl:attribute-set name="base-font">
    <xsl:attribute name="font-size"><xsl:value-of select="$default-font-size"/></xsl:attribute>
</xsl:attribute-set>
```

I think you should be able to override this by setting the attribute to another value:

```xsl
<xsl:attribute name="font-size">18pt</xsl:attribute>
```

**Comment by hcw70** [comment]
Thanks for the info. Part of my problem was that the requested (copyrighted windows only) fonts were not found under (open source) Linux.
So i adapted the font mapping and now the codeblock font looks better.

Regards Hauke
