### ISSUE TITLE
Using codeblocks with dita-ot 3.7.2 raises error messages

### ISSUE THREAD

**Issue by hcw70** [jason-fox/fox.jason.prismjs#13]
Whenever i use a highlighted codeblock
```
            <codeblock outputclass="language-cpp">  int main() { Test codeblock; }
             </codeblock>
```
in a dita topic i get the error
`
 [pipeline] An error occurred matching pattern {element()[Q{http://dita-ot.sourceforge.net/ns/201007/dita-ot}matches-searchtitle-class(exactly-one((attribute::attribute(Q{}class)) treat as attribute(Q{}class)))]}: An empty sequence is not allowed as the first argument of dita-ot:matches-searchtitle-class()
`
several times when doing a pdf output.

The pdf itself however does not seem to have issues.

**Comment by jason-fox** [comment]
It appears to be unnecessary processing when reflecting the prism colors when generating PDFs. Could you pull and see if [981deaa](https://github.com/jason-fox/fox.jason.prismjs/commit/981deaac56ca8fa4897877b83f58d28e95687047) has fixed it for you?

```console
dita install https://github.com/jason-fox/fox.jason.prismjs/archive/master.zip
```

**Comment by hcw70** [comment]
Yes, that fixes the issue. 

Thank you for that fix!

Regards
