### ISSUE TITLE
Syntax highlighted only when debug attributes are generated

### ISSUE THREAD

**Issue by skulle** [jason-fox/fox.jason.prismjs#5]
If you set `generate-debug-attributes` to `false` no code is highlighted. If you set it to `true` it is working fine.

Tested with the sample content provided by the plugin and dita-ot 3.6.

**Comment by jason-fox** [comment]
This is correct, the current highlighting code relies on the presence of the `xtrc` attribute: see [here](https://github.com/jason-fox/fox.jason.prismjs/blob/master/resource/antlib.xml#L162-L165) 

It should be possible to fix this by generating some other temporary id attributes for `codeblock` and `codeph` elements and use those as a hook instead.

**Comment by skulle** [comment]
Thanks for the info. May be I am going to try that since we are normally disabling debug attributes, because of performance reasons, for our production environments. Anyway thanks again for the info.

**Comment by jason-fox** [comment]
You could start with something like: [this work-in-progress](https://github.com/jason-fox/fox.jason.prismjs/tree/feature/add-ids) - it basically works but can cause memory issues.

**Comment by jason-fox** [comment]
Fixed with removing XMLTask dependency

```console
dita install https://github.com/jason-fox/fox.jason.extend.css/archive/master.zip
```

**Comment by skulle** [comment]
Cool, that is great news. Thanks for this quick fix :)
