### ISSUE TITLE
java.net.MalformedURLException

### ISSUE THREAD

**Issue by logronio** [jason-fox/fox.jason.prismjs#6]
I am getting this malformed url error when dita file contains codeblock/codeph. Did I missed some configurations?
Posted below is the error log.

`\dita-ot-3.6\plugins\fox.jason.prismjs\xsl\add-code-id.xsl:65:89: Fatal Error! Resolved URL is malformed Cause: java.net.MalformedURLException: unknown protocol: d`

Tested with the sample content provided by the plugin and dita-ot 3.6.

**Comment by jason-fox** [comment]
Can you run the sample in debug mode (e.g.  `dita -d -f html5 -i XXX -o YYY`) and paste your debug trace here?

**Comment by logronio** [comment]
[error.txt](https://github.com/jason-fox/fox.jason.prismjs/files/6301573/error.txt)

**Comment by jason-fox** [comment]
It looks like this is a Window specific bug - the filepath needs adjusting see [this](https://stackoverflow.com/questions/8474694/java-url-unknown-protocol-c)

**Comment by jason-fox** [comment]
Try altering `resource/antlib.xml` as shown here:  31d26a5f - it will attempt to alter the path and provide more debug.  The filter mapping may need to be changed to get the right number of slashes in the filepath.

Could you make the change and see if one, two or three slashes are needed.

```console
dita -d -f html5 -i XXX -o YYY
```

**Comment by logronio** [comment]
It works with 
`<pathconvert targetos="unix" property="prism.temp.dir.unix" >
        <path location="${prism.temp.dir}"/>
        <filtermapper>
          <replacestring from="\" to="/" />
        </filtermapper>
        <map from="C:" to="file:///C:"/>
        <map from="D:" to="file:///D:"/>
      </pathconvert>
      <echo level="error" message="${prism.temp.dir.unix}" />`

Can this change be included in the future release?

**Comment by jason-fox** [comment]
Please reinstall from `master`:

```console
dita uninstall fox.jason.prismjs
dita install https://github.com/jason-fox/fox.jason.prismjs/archive/master.zip
```

And if you can confirm that works I can make a release.

**Comment by logronio** [comment]
Yes, it works. Thanks!
