### ISSUE TITLE
Weird characters appearing instead of highlighted codes

### ISSUE THREAD

**Issue by logronio** [jason-fox/fox.jason.prismjs#7]
Tested with the sample content provided by the plugin and dita-ot 3.6. Please see attached pdf.
[document.pdf](https://github.com/jason-fox/fox.jason.prismjs/files/6340864/document.pdf)

It seems related to the last change, it looks like the converted path is the same through out the process. It is evident in the temporary code directory, all temporary files created intended for another content were all stored in the same directory.

**Comment by jason-fox** [comment]
The unix path wasn't recalculated each time for each page. Please reinstall from `master`:

```console
dita uninstall fox.jason.prismjs
dita install https://github.com/jason-fox/fox.jason.prismjs/archive/master.zip
```

I have created a 3.2.2 release.
