### ISSUE TITLE
Add validation to check if file exist

### ISSUE THREAD

**Issue by logronio** [jason-fox/fox.jason.prismjs#9]
Logs:
`highlight:
File file:/C:/test/content/authoring/fht1600964327060.dita not found
    [mkdir] Created dir: C:\test\output\pdf\agw1600983740990\temp\code\6a2d1d117e2bbc05d2e2d9f8a10834fffa9991f0.dita
[add-code-id] Processing C:\test\output\pdf\agw1600983740990\temp\6a2d1d117e2bbc05d2e2d9f8a10834fffa9991f0.dita to C:\test\output\pdf\agw1600983740990\temp\null1209384693
[add-code-id] Loading stylesheet C:\test\dita-ot-3.6\plugins\fox.jason.prismjs\xsl\add-code-id.xsl
     [copy] Copying 1 file to C:\test\output\pdf\agw1600983740990\temp
    [mkdir] Created dir: C:\test\output\pdf\agw1600983740990\temp\code\6c3101787579d7391d35046d96ee15652f4d0448.dita
[add-code-id] Processing C:\test\output\pdf\agw1600983740990\temp\6c3101787579d7391d35046d96ee15652f4d0448.dita to C:\test\output\pdf\agw1600983740990\temp\null1095678966
[add-code-id] Loading stylesheet C:\test\dita-ot-3.6\plugins\fox.jason.prismjs\xsl\add-code-id.xsl
     [copy] Copying 1 file to C:\test\output\pdf\agw1600983740990\temp
    [mkdir] Created dir: C:\test\output\pdf\agw1600983740990\temp\code\7945d282ecb24c73121a3dea48f9848bafbf69be.xml
[add-code-id] Processing C:\test\output\pdf\agw1600983740990\temp\7945d282ecb24c73121a3dea48f9848bafbf69be.xml to C:\test\output\pdf\agw1600983740990\temp\null988992216
[add-code-id] Loading stylesheet C:\test\dita-ot-3.6\plugins\fox.jason.prismjs\xsl\add-code-id.xsl
     [copy] Copying 1 file to C:\test\output\pdf\agw1600983740990\temp
    [mkdir] Created dir: C:\test\output\pdf\agw1600983740990\temp\code\afc34bcc0d413352fb10fb5fa0cda06e742970d9.dita
[add-code-id] Processing C:\test\output\pdf\agw1600983740990\temp\afc34bcc0d413352fb10fb5fa0cda06e742970d9.dita to C:\test\output\pdf\agw1600983740990\temp\null171970911
[add-code-id] Loading stylesheet C:\test\dita-ot-3.6\plugins\fox.jason.prismjs\xsl\add-code-id.xsl
     [copy] Copying 1 file to C:\test\output\pdf\agw1600983740990\temp
    [mkdir] Created dir: C:\test\output\pdf\agw1600983740990\temp\code\ike1591695086339.xml
[add-code-id] Processing C:\test\content\published\en-us\uvy1582744299765.ditamap_23\ike1591695086339.xml to C:\test\output\pdf\agw1600983740990\temp\null892913150
[add-code-id] Loading stylesheet C:\test\dita-ot-3.6\plugins\fox.jason.prismjs\xsl\add-code-id.xsl
[add-code-id] : Error! I/O error reported by XML parser processing file:/C:/test/content/published/en-us/uvy1582744299765.ditamap_23/ike1591695086339.xml: C:\test\content\published\en-us\uvy1582744299765.ditamap_23\InfineonDitabase.dtd (The system cannot find the file specified) Cause: java.io.FileNotFoundException: C:\test\content\published\en-us\uvy1582744299765.ditamap_23\InfineonDitabase.dtd (The system cannot find the file specified)
[add-code-id] Failed to process C:\test\content\published\en-us\uvy1582744299765.ditamap_23\ike1591695086339.xml`

Is it possible to add validation to check if a file exists? Or prevent it from failing or stopping the output generation, maybe a warning would suffice.

**Comment by jason-fox** [comment]
I assume this is running under Windows, as it appears that the DTD is not being resolved correctly. I've never seen this occur on Unix-based systems. You could get around this by ensuring that the `InfineonDitabase.dtd` can be found somewhere - it doesn't even have to be a proper DTD, an empty file will suffice.
surffice

Somewhere in your `*.dita` you have the following DTD declaration:

```xml
<!DOCTYPE topic PUBLIC "-//OASIS//DTD SOMETHING/SOMETHING" "InfineonDitabase.dtd">
```

Amend the [`<xslt taskname="add-code-id">`](https://github.com/jason-fox/fox.jason.prismjs/blob/master/resource/antlib.xml#L302-L314) call in `resource/antlib.xml` to include a `<xmlcatalog>` element pointing to an existing file. Personally I'd just add an empty file called `resource/fake.dtd`

```xml
<xmlcatalog id="fake.dita.catalog">
    <catalogpath path="${dita.plugin.org.dita.base.dir}/catalog-dita.xml"/>
    <dtd publicId="-//OASIS//DTD DITA SOMETHING/SOMETHING" location="${dita.plugin.fox.jason.prismjs.dir}/resource/fake.dtd" />
</xmlcatalog>

<xslt taskname="add-code-id" in="@{file}" out="${prismjs.temp.xml}" style="${dita.plugin.fox.jason.prismjs.dir}/xsl/add-code-id.xsl">
         <xmlcatalog refid="fake.dita.catalog"/>
         <param expression="${prism.temp.dir.unix}" name="CODE_DEST"/>
         <param expression="${prism.default}" name="PRISM_DEFAULT" if="prism.default"/>
</xslt>
```

You can see an example of this technique in the [pretty-dita plugin](https://github.com/jason-fox/fox.jason.pretty-dita/blob/master/src/main/resources/fox/jason/prettydita/antlib.xml#L47)

**Comment by jason-fox** [comment]
Maybe this change - ceee31a is sufficient for you. Both the PDF and HTML transforms define the catalogue path as shown:

```xml
<path id="xml.catalog.path">
      <pathelement location="${customization.dir}/catalog.xml"/>
      <pathelement location="${dita.plugin.org.dita.pdf2.dir}/cfg/catalog.xml"/>
      <pathelement location="${dita.plugin.org.dita.base.dir}/catalog-dita.xml"/>
</path>
<xmlcatalog id="xml.catalog">
     <catalogpath refid="xml.catalog.path"/>
</xmlcatalog>
```

So if necessary you could [Extending the XML catalog file](https://www.dita-ot.org/dev/topics/plugin-xmlcatalog.html)

**Comment by logronio** [comment]
Thanks. Adding the correct catalog fix the problem.
